import { prisma } from './prisma';
import { AIGeneratedFlashcard } from './ai/cloudAIGenerator';

/**
 * Save AI-generated flashcards to database
 */
export async function saveAIGeneratedFlashcards({
  flashcards,
  userId,
  chapterId,
}: {
  flashcards: AIGeneratedFlashcard[];
  userId: string;
  chapterId: string;
}) {
  if (!flashcards || flashcards.length === 0) {
    return;
  }

  await prisma.flashcard.createMany({
    data: flashcards.map((card) => ({
      userId,
      chapterId,
      questionKm: card.question,
      answerJson: {
        answer: card.answer,
      },
      isUserGenerated: false, // generated by system/AI
    })),
  });
}
